#include <iostream>
// #include <fstream>
#include <string>
#include <array>

#include "headers/de_allocate.hpp"
#include "headers/iof.hpp"
#include "headers/eq_sol_id_gas.hpp"

using namespace std;

/*
    Numerical solution of equations 
    one-dimensional ideal gas dynamics (GD) 
    with adiabatic exponent 𝛾 =5/3 
    using Harten-Lax-van Leer (HLL) method.
*/

int main ()
{
// Add test selection for single compilation

    string test = "";

    while (true)
    {
        cout << "Choose a test!\nPossible input options: 1, 2, 3\n";
        cin >> test;
        cout << '\n';

        test = "input" + test + ".txt";

        if (!((test == "input1.txt") || (test == "input2.txt") || (test == "input3.txt")))
        {
            cerr << "Invalid input!\n";
        }
        else
        {
            break;
        }
    }

// Parameter initialization:
//    rho_L (rho_R) = gas density on the left (on the right),
//    v_L   (v_R)   = gas velocity on the left (on the right),
//    p_L   (p_R)   = gas pressure on the left (on the right).

    double rho_L, v_L, p_L, rho_R, v_R, p_R;
    
    initialization(test, rho_L, v_L, p_L, rho_R, v_R, p_R);

    // moment of time (Саша говорил что-то про то, что это должно быть переменное значение)
    double time = 0.10;

/*
    Since there is a gamma() in C++, let’s replace the letter γ with the third letter of the
    Phoenician alphabet 𐤂 (gimel) that generates it.
*/
    constexpr double gimel = 5.0 / 3.0; // Ratio of specific heats (adiabatic exponent)

// Continued definition of parameters

    // (rho, v, p) left and right
    array<array<double, 3>, 2> u0; // массив u0 размером 3x2

    // selecting the number of grid cells (N) and the Courant number (C)
    int N = 40;      // 40, 80, 160, 320      // Хз, как для случая A считать число Куранта (!!!)
    double C = 0.3;  // 0.3, 0.6, 0.9

    // coordinate borders
    const double x_L = -0.5;
    const double x_R = 0.5;
    // delta x (это видимо шаг)
    double dx = (x_R - x_L) / N;
// daniel:
    int N0 = N / 2 + 1; // что за zero index, я пока не пон
    // Number of nods
    int64_t number_of_nods = N + 1; // пока тоже не ясно, это используется в определении массива

/*  
    хз, надо ли проверять начальные условия для определения конфинурации и на условие вакуума.
   -ну вообще я не видела разделения на конфигурации... пока не могу ничего сказать
*/
    // // The pressure positivity condition is tested for
    // if ((2.0 / (adiabat - 1.0)) * (c_l + c_r) <= (v_r - v_l))
    // {
    //     //  The initial data is such that vacuum is generated.
    //     //  Program stopped.
    //     cout << "Vacuum is generated by data. Program stopped."<< endl;
    //     return 3;
    // }


// Allocation of memory to dynamic variables

    double * x = create_vector(number_of_nods + 2); // т.е. по факту это вектор длиной N+3
    double * P = create_vector(number_of_nods + 2);
    double * RO = create_vector(number_of_nods + 2);
    double * V = create_vector(number_of_nods + 2);

    double ** u = create_array(3, number_of_nods + 2);
    double ** F = create_array(3, number_of_nods + 2);

    for (size_t i = 0; i < number_of_nods + 2; ++i)
        x[i] = x_L + (i - 1) * dx;

    string suffix = "";

    // set_initial_values(ro, v, p);
    suffix = "Start";
    // make_dat(x, ro, v, p, suffix);
    // real_to_u(u, ro, v, p);
    // real_to_F(F, ro, v, p);
    // godunov(u, F);
    // u_to_real(u, ro, v, p);
    suffix = "Stop";
    // make_dat(x, ro, v, p, suffix);

    free_vector(x);
    free_vector(P);
    free_vector(RO);
    free_vector(V);

    free_array(u);
    free_array(F);

    return 0;

}